arrow_left = '◀'
arrow_right = '➡'
world = '🌎'
underage = '🔞'
gear = '⚙'
eyes = '👀'
book = '📖'
new = '🆕'
checked = '✅'
stop = '❌'
search = '🔎'

# peoples
couple = '👫'
woman_office = '👩‍💼'
man_office = '👨‍💼'
woman = '👩'
man = '👨'
person = '👤'
persons = '👥'
hand_over_mouth = '🤭'


# flags
russia_flag = '🇷🇺'
ukraine_flag = '🇺🇦'
belarus_flag = '🇧🇾'
kazakhstan_flag = '🇰🇿'
uzbekistan_flag = '🇺🇿'
tajikistan_flag = '🇹🇯'
turkmenistan_flag = '🇹🇲'
azerbaijan_flag = '🇦🇿'
armenia_flag = '🇦🇲'
moldova_flag = '🇲🇩'

